### ISSUE TITLE
High memory and disk usage of splash requests

### ISSUE THREAD

**Issue by lopuhin** [TeamHG-Memex/undercrawler#30]
It seems that currently requests queue takes a lot of memory if running without ``JOBDIR``, and a lot of disk space when running with ``JOBDIR``.

Result of memory profiling after some time:
Site 1 (after maybe 10k pages fetched?):
```
In [7]: summary.print_(sum1)
                                        types |   # objects |   total size
============================================= | =========== | ============
                                 <class 'dict |      325334 |    122.44 MB
                                  <class 'str |      891057 |     66.60 MB
                                 <class 'list |      140968 |     43.73 MB
          <class 'scrapy.http.headers.Headers |      101893 |     27.99 MB
                              <class 'weakref |      310643 |     23.70 MB
                                <class 'bytes |      209461 |     15.84 MB
                            <class 'frozenset |         260 |     11.85 MB
                                  <class 'int |      371624 |      9.94 MB
                                  <class 'set |       10030 |      9.68 MB
             <class 'urllib.parse.ParseResult |      101387 |      9.28 MB
                               <class 'method |      104241 |      6.36 MB
  <class 'scrapy_splash.request.SplashRequest |      101885 |      5.44 MB
                        <class 'numpy.ndarray |        6641 |      3.91 MB
                                 <class 'type |        3036 |      3.08 MB
                                 <class 'code |       20056 |      2.76 MB

In [8]: len(spider.crawler.engine.slot.scheduler)
Out[8]: 100736
```
Here most memory is taken by dicts (request.meta and inner dicts), and also some by str.

Site 2 is different: here request queue is 10x smaller, but it takes the same amount of memory (after maybe 2k-3k pages fetched):
```
                                types |   # objects |   total size
===================================== | =========== | ============
                        <class 'bytes |       19726 |    127.90 MB
                          <class 'str |      213742 |     21.45 MB
                         <class 'dict |       44710 |     20.86 MB
                    <class 'frozenset |         257 |     11.84 MB
                          <class 'int |      369817 |      9.90 MB
                         <class 'list |       22572 |      5.54 MB
                          <class 'set |        4424 |      4.68 MB
                         <class 'type |        3012 |      3.05 MB
                         <class 'code |       20042 |      2.75 MB
  <class 'scrapy.http.headers.Headers |        9248 |      2.54 MB
                      <class 'weakref |       32766 |      2.50 MB
                <class 'numpy.ndarray |        2077 |      1.23 MB
                        <class 'tuple |       12974 |    858.53 KB
     <class 'urllib.parse.ParseResult |        8628 |    808.88 KB
                       <class 'method |       10662 |    666.38 KB

len(spider.crawler.engine.slot.scheduler)
9212
```
In this case, bytes take more space (these are encoded requests to splash), because there are a lot of cookies on the site.

When using ``JOBDIR``, the main offenders are our lua and js scripts, that are repeated for each request.

This is not very severe I think. And maybe not directly related to an issue I noticed this morning, when scrapy process for Site 2 (having crawled 35k pages) was using about 8 Gb of RAM (using JOBDIR, although the server could be low on disk space at the time).

**Comment by kmike** [comment]
I think it could be possible to somewhat reduce this memory (2x?) by making `meta['_splash_processed']` a bool flag, not a copy of `meta['splash']` in scrapy-splash. It is not a deep copy anyways now (https://github.com/scrapy-plugins/scrapy-splash/blob/623b98b2b78c2e64d90cb6d7707cc2883f306560/scrapy_splash/middleware.py#L150), this is just a waste.

To avoid passing Lua and JS with each request something similar to https://github.com/scrapinghub/splash/issues/283 should be implemented in Splash. Alternatively, we can deploy Splash with our script as a custom module (http://splash.readthedocs.org/en/latest/scripting-libs.html#adding-your-own-modules), but this is less flexible.

**Comment by kmike** [comment]
I'll try to fix scrapy-splash `_splash_processed` issue soon.

**Comment by lopuhin** [comment]
I was thinking of some lazy processing of requests: we keep just an URL and some minimal info, and make it a fully-featured request just before it is made. But I'm not sure this will work.

**Comment by kmike** [comment]
Hm, it could work, but a Splash feature similar to EVAL/EVALSHA in redis (http://redis.io/commands/EVAL) will make it unnecesary.

**Comment by kmike** [comment]
`_splash_processed` fix is here: https://github.com/scrapy-plugins/scrapy-splash/pull/61

**Comment by lopuhin** [comment]
This is fixed now, thanks @kmike ! 👍
