### ISSUE TITLE
spider can't be stopped with Ctrl-C when autologin is pending

### ISSUE THREAD

**Issue by kmike** [TeamHG-Memex/undercrawler#35]
It is hard to stop the spider if it uses autologin and autologin is responding with 'pending' status; I had to `kill -9` it.

**Comment by lopuhin** [comment]
Yeah, that's really annoying (I even learnt a trick with ``Ctrl-\`` for sending a SIGQUIT, which also stops it).

**Comment by lopuhin** [comment]
Fixed in the nonblocking autologin middleware #46

**Comment by lopuhin** [comment]
Fixed in #46

**Comment by lopuhin** [comment]
Fixed by #46 (sorry for the noise, GH seems to have issues with write consistency)
