### ISSUE TITLE
An option to run without splash

### ISSUE THREAD

**Issue by lopuhin** [TeamHG-Memex/undercrawler#50]
I think it could be useful if we just want to crawl some sites without tor and heavy js usage, and to compare results with/without splash. It should be not too hard to support it, since we can just run all tests in two different configurations. What do you think @kmike ?

**Comment by kmike** [comment]
+1

**Comment by lopuhin** [comment]
I think this was done long ago, just passing ``-s SPLASH_URL=`` from the command line works, and it's default when running via arachnado
