### ISSUE TITLE
S3 Filestorage

### ISSUE THREAD

**Issue by thebennos** [TeamHG-Memex/undercrawler#59]
I am trying to save files to S3, but could not get it up and running. 

"s3://bucket/prefix/"  need to be defined but where?
In the UI is 
Scrapy settings
and 
Spider Args. 
Looks like nothing works. 
Need to know, where  AWS Key and AWS Secret needs to be defined and how to set the filestorage to "s3://bucket/prefix/". 

A little bit help would be cool.

**Comment by lopuhin** [comment]
Hello @thebennos , S3 filestorage is set with ``FILES_STORE`` setting - you can pass it via command line, see scrapy docs: https://doc.scrapy.org/en/latest/topics/settings.html?highlight=settings#command-line-options. AWS access params can be set with ``AWS_ACCESS_KEY_ID`` and ``AWS_SECRET_ACCESS_KEY`` setting variables (so the way to pass them is the same).

**Comment by thebennos** [comment]
thx, 
I can set it via commandline and it works, but I do not get it working as docker image.

**Comment by thebennos** [comment]
To make it sure. 
Setting the FILES_STORE and the AWS credentials, stores the files and not the CDR?
CDR is just saved to mongodb?

**Comment by lopuhin** [comment]
Yes, FILES_STORE influences only the files. Items in CDR formats are stored to plain files, mongodb is not used here.
There is a ``dockerize-arachnado`` branch that uses Arachnado as a crawler UI, if you are using it, then items should be stored into mongodb.
