### ISSUE TITLE
Config/issues with running multiple crawls?

### ISSUE THREAD

**Issue by nehakansal** [TeamHG-Memex/undercrawler#74]
If I run multiple crawls at the same time using Undercrawler + Aquarium, could be multiple crawls to the same url or different urls, theoretically what issues I might run into, if any? And also, are there any specific config settings that would be helpful for this scenario?

**Comment by lopuhin** [comment]
@nehakansal multiple crawls should be fine, assuming they are run from separate python processes, writing output to separate files. Aquarium and autologin servers can be shared. If separate crawls crawl different domains, then I don't think there are any config variables that need special treatment. If multiple crawls apply to the same domain, then crawling concurrency settings might need adjustment.

I think we did run multiple undercrawler jobs on one machine and didn't run into any issues.

**Comment by nehakansal** [comment]
Thank you!, thats good to know.
