### ISSUE TITLE
How can i get both cookie and html through def parse(self,response)

### ISSUE THREAD

**Issue by bswbatman** [TeamHG-Memex/undercrawler#78]
hi,
**How can i get both `cookie `and `html `through `def parse(self,response)`**

I only can get one field of render like `return render['html']`  or  `return render['har']` or `return render['cookiejar']` 

In the official `H-H.lua` , splash can `return render` ,and the `render `get all fields I want, not only one of the field,but all of them.

I don't `def parse(self,response)` how to use this object

![snipaste_2018-08-28_11-17-59](https://user-images.githubusercontent.com/16164964/44698823-1ea89500-aab4-11e8-9252-e9eae6cf75e4.png)

` def parse(self, response):

     print(type(response))
     print(dir(response))
`
I tried use #['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__'.... , seem like no method I need.

thx.

**Comment by lopuhin** [comment]
Hey, in the lua script you can have ``return render``, and then in ``parse`` method in python you can use ``response.data['html']`` and ``response.data['har']``

**Comment by bswbatman** [comment]
Thanks
