### ISSUE TITLE
How to set splash.plugins_enabled for Undercrawler.

### ISSUE THREAD

**Issue by nehakansal** [TeamHG-Memex/undercrawler#82]
Hi, I am having issues trying to crawl couple of sites. I read about the splash.plugins_enabled setting, and I would like to turn it on to see if that fixes the crawling issue I am running into. How would I turn it on in Undercrawler? Thanks.

**Comment by lopuhin** [comment]
Hi @nehakansal , you can add it to the code here https://github.com/TeamHG-Memex/undercrawler/blob/e5104dca5a5d9fe4b9ddd085c7b0935a712ea74d/undercrawler/directives/headless_horseman.lua#L35, and you can set it from python in a similar way to how ``images_enabled`` is handled

**Comment by nehakansal** [comment]
Got it, thank you!

**Comment by lopuhin** [comment]
Glad you solved it!
